### PR TITLE
Krampus improvements and Detectoclown bug fix

### LINKED ISSUE #10: Krampus - Improvements to be made
- [x] Add sound when player struggles so it's more obvious that something is happening
- [x] Add message like "Krampus has a hold of you" above the struggle bar
- [x] Adjust "Press W to struggle" label to make it clearer that you have to press repeatedly. Maybe "Mash W to struggle"
  - Maybe change inside label to "Escape progress" and add a new label above or below that says "Repeatedly press W to struggle"
- [x] Stop thirdperson jumping animation for player being carried
- [x] Attempt to make victim camera following (e.g. matching Krampus' angles) less jerky
- [x] Add maximum attempts to the drop logic so there aren't infinite loops
  - Move them onto krampus if that happens

### LINKED ISSUE #13: Detectoclown - Name is not updated on the server

### PR DESCRIPTION
**Pull request by Malivil**
**Krampus**
- Changed krampus victim escape progress labels to be clearer
- Changed krampus victim to not be animated so it doesn't look like they are jumping all the time
- Changed krampus victim release logic to prevent deadlocks
- Added sounds when a krampus carry victim is struggling
- Added camera movement dampening to smooth camera changes while being carried by the krampus
- Fixed krampus' victim's camera angles following krampus' camera angles during the post-release delay time

Closes #10

**Detectoclown**
- Added a delay to the detectoclown name client call to fix it not updating properly

Fixes #13

### CODE REVIEW

File: gamemodes/terrortown/entities/weapons/weapon_kra_carry.lua [hunk 1]
```diff
@@ -353,10 +394,42 @@ if CLIENT then
...
+            -- This lock takes effect in the delay after the victim is dropped by the Krampus
+            if client:GetNWBool("KrampusCarryVictim", false) then
+                local currentYaw = client:EyeAngles().yaw
+                local targetYaw = krampus:EyeAngles().yaw
+
+                local speedMult = 0.001
+                local minSpeed = 0.001
+
+                local dir = currentYaw < targetYaw and 1 or -1
+                local difference = math.abs(currentYaw - targetYaw)
```
Comment (NoxxFlame) [inline gamemodes/terrortown/entities/weapons/weapon_kra_carry.lua:408]: We can cache this method
```suggestion
                local difference = MathAbs(currentYaw - targetYaw)
```

File: gamemodes/terrortown/entities/weapons/weapon_kra_carry.lua [hunk 2]
```diff
@@ -13,6 +13,7 @@ local util = util
 local AddHook = hook.Add
 local EntsFindAlongRay = ents.FindAlongRay
 local MathClamp = math.Clamp
+local MathRandom = math.random
```
Comment (NoxxFlame) [inline gamemodes/terrortown/entities/weapons/weapon_kra_carry.lua:16]:
```suggestion
local MathRandom = math.random
local MathAbs = math.abs
```

**Review by NoxxFlame — CHANGES_REQUESTED** [review]
`math.abs` can be cached but everything else LGTM
